from __future__ import annotations

from app.main.utils.constants import MAP_STYLES, ROOT

HEATMAP_PAGE_TITLE = "Heatmap"
HEATMAP_PAGE_ICON = "📍"
HEATMAP_DEFAULT_METRIC = "cost"
HEATMAP_METRICS = ("cost", "emissions")
HEATMAP_SURFACE_MODE_DEFAULT = "2d"
HEATMAP_SURFACE_MODES = ("2d", "3d")
HEATMAP_DESTINATIONS_PATH = ROOT / "data" / "processed" / "destinies" / "city_dests_over50k.txt"
HEATMAP_DESTINATION_SET_ID = HEATMAP_DESTINATIONS_PATH.name
HEATMAP_DESTINATION_LABEL = "Cities with population over 50k"
HEATMAP_BRAZIL_BOUNDARY_PATH = ROOT / "data" / "processed" / "geo" / "brazil_boundary_simplified.geojson"
HEATMAP_BRAZIL_CENTER_LAT = -14.2350
HEATMAP_BRAZIL_CENTER_LON = -51.9253
HEATMAP_BRAZIL_ZOOM = 3.4
HEATMAP_3D_PITCH = 44
HEATMAP_3D_BEARING = 18
HEATMAP_MAP_STYLE = MAP_STYLES["Voyager"]
HEATMAP_COLOR_NEGATIVE = (188, 55, 45)
HEATMAP_COLOR_MID = (243, 210, 102)
HEATMAP_COLOR_POSITIVE = (34, 139, 84)
HEATMAP_SURFACE_ALPHA = 210
HEATMAP_SURFACE_CELL_SIZE_DEGREES = 0.65
HEATMAP_SURFACE_IDW_POWER = 1.75
HEATMAP_SURFACE_IDW_NEIGHBORS = 12
HEATMAP_SURFACE_COLOR_QUANTILE = 0.90
HEATMAP_SURFACE_ELEVATION_QUANTILE = 0.95
HEATMAP_SURFACE_MAX_ELEVATION_M = 60_000.0
HEATMAP_POINT_OVERLAY_RADIUS_M = 22_000.0
