from __future__ import annotations

from app.main.utils.constants import MAP_STYLES, ROOT

HEATMAP_PAGE_TITLE = "Heatmap"
HEATMAP_PAGE_ICON = "📍"
HEATMAP_DEFAULT_METRIC = "cost"
HEATMAP_METRICS = ("cost", "emissions")
HEATMAP_DESTINATIONS_PATH = ROOT / "data" / "processed" / "destinies" / "city_dests_over50k.txt"
HEATMAP_DESTINATION_SET_ID = HEATMAP_DESTINATIONS_PATH.name
HEATMAP_DESTINATION_LABEL = "Cities with population over 50k"
HEATMAP_BRAZIL_BOUNDARY_PATH = ROOT / "data" / "processed" / "geo" / "brazil_boundary_simplified.geojson"
HEATMAP_BRAZIL_CENTER_LAT = -14.2350
HEATMAP_BRAZIL_CENTER_LON = -51.9253
HEATMAP_BRAZIL_ZOOM = 3.7
HEATMAP_3D_PITCH = 67
HEATMAP_3D_BEARING = 34
HEATMAP_MAP_STYLE = MAP_STYLES["Voyager"]
HEATMAP_COLOR_NEGATIVE = (203, 96, 48)
HEATMAP_COLOR_MID = (236, 214, 118)
HEATMAP_COLOR_POSITIVE = (106, 156, 67)
HEATMAP_SURFACE_ALPHA = 210
HEATMAP_SURFACE_CELL_SIZE_DEGREES = 0.65
HEATMAP_SURFACE_COLOR_QUANTILE = 0.88
HEATMAP_SURFACE_ELEVATION_QUANTILE = 0.58
HEATMAP_SURFACE_MAX_ELEVATION_M = 310_000.0
HEATMAP_SURFACE_ELEVATION_FLOOR_RATIO = 0.01
HEATMAP_SURFACE_ELEVATION_GAMMA = 0.42
HEATMAP_POINT_OVERLAY_RADIUS_M = 22_000.0
